READING_PLANS = {
    "proverbs-31": {
        "id": "proverbs-31",
        "title_en": "Proverbs in 31 Days",
        "title_ta": "31 நாட்களில் நீதிமொழிகள்",
        "tagline": "Wisdom for daily living • 1 Chapter a day",
        "total_days": 31,
        "badge": "Wisdom",
        "days": [
            {"day": d, "book_id": 20, "chapter": d, "ref": f"Proverbs {d} / நீதிமொழிகள் {d}"}
            for d in range(1, 32)
        ],
    },
    "nt-90": {
        "id": "nt-90",
        "title_en": "New Testament in 90 Days",
        "title_ta": "90 நாட்களில் புதிய ஏற்பாடு",
        "tagline": "Gospels, Acts & Epistles • ~3 Chapters a day",
        "total_days": 90,
        "badge": "Canonical",
        "days": [
            # 260 NT chapters divided across 90 days
            {"day": 1, "book_id": 40, "chapter": 1, "ref": "Matthew 1-3"},
            {"day": 2, "book_id": 40, "chapter": 4, "ref": "Matthew 4-6"},
            {"day": 3, "book_id": 40, "chapter": 7, "ref": "Matthew 7-9"},
            {"day": 4, "book_id": 40, "chapter": 10, "ref": "Matthew 10-12"},
            {"day": 5, "book_id": 40, "chapter": 13, "ref": "Matthew 13-15"},
            {"day": 6, "book_id": 40, "chapter": 16, "ref": "Matthew 16-18"},
            {"day": 7, "book_id": 40, "chapter": 19, "ref": "Matthew 19-21"},
            {"day": 8, "book_id": 40, "chapter": 22, "ref": "Matthew 22-24"},
            {"day": 9, "book_id": 40, "chapter": 25, "ref": "Matthew 25-28"},
            {"day": 10, "book_id": 41, "chapter": 1, "ref": "Mark 1-3"},
            {"day": 11, "book_id": 41, "chapter": 4, "ref": "Mark 4-6"},
            {"day": 12, "book_id": 41, "chapter": 7, "ref": "Mark 7-9"},
            {"day": 13, "book_id": 41, "chapter": 10, "ref": "Mark 10-12"},
            {"day": 14, "book_id": 41, "chapter": 13, "ref": "Mark 13-16"},
            {"day": 15, "book_id": 43, "chapter": 1, "ref": "John 1-3"},
            {"day": 16, "book_id": 43, "chapter": 4, "ref": "John 4-6"},
            {"day": 17, "book_id": 43, "chapter": 7, "ref": "John 7-9"},
            {"day": 18, "book_id": 43, "chapter": 10, "ref": "John 10-12"},
            {"day": 19, "book_id": 43, "chapter": 13, "ref": "John 13-16"},
            {"day": 20, "book_id": 43, "chapter": 17, "ref": "John 17-21"},
            {"day": 21, "book_id": 44, "chapter": 1, "ref": "Acts 1-3"},
            {"day": 22, "book_id": 44, "chapter": 4, "ref": "Acts 4-6"},
            {"day": 23, "book_id": 44, "chapter": 7, "ref": "Acts 7-9"},
            {"day": 24, "book_id": 44, "chapter": 10, "ref": "Acts 10-12"},
            {"day": 25, "book_id": 44, "chapter": 13, "ref": "Acts 13-15"},
            {"day": 26, "book_id": 44, "chapter": 16, "ref": "Acts 16-18"},
            {"day": 27, "book_id": 44, "chapter": 19, "ref": "Acts 19-21"},
            {"day": 28, "book_id": 44, "chapter": 22, "ref": "Acts 22-25"},
            {"day": 29, "book_id": 44, "chapter": 26, "ref": "Acts 26-28"},
            {"day": 30, "book_id": 45, "chapter": 1, "ref": "Romans 1-4"},
        ],
    },
    "psalms-comfort": {
        "id": "psalms-comfort",
        "title_en": "Psalms for Peace & Comfort",
        "title_ta": "தேறுதலின் சங்கீதங்கள்",
        "tagline": "Selected Psalms for prayer and reflection • 30 Days",
        "total_days": 30,
        "badge": "Devotional",
        "days": [
            {"day": 1, "book_id": 19, "chapter": 1, "ref": "Psalm 1 / சங்கீதம் 1"},
            {"day": 2, "book_id": 19, "chapter": 23, "ref": "Psalm 23 / சங்கீதம் 23"},
            {"day": 3, "book_id": 19, "chapter": 27, "ref": "Psalm 27 / சங்கீதம் 27"},
            {"day": 4, "book_id": 19, "chapter": 34, "ref": "Psalm 34 / சங்கீதம் 34"},
            {"day": 5, "book_id": 19, "chapter": 46, "ref": "Psalm 46 / சங்கீதம் 46"},
            {"day": 6, "book_id": 19, "chapter": 51, "ref": "Psalm 51 / சங்கீதம் 51"},
            {"day": 7, "book_id": 19, "chapter": 63, "ref": "Psalm 63 / சங்கீதம் 63"},
            {"day": 8, "book_id": 19, "chapter": 91, "ref": "Psalm 91 / சங்கீதம் 91"},
            {"day": 9, "book_id": 19, "chapter": 103, "ref": "Psalm 103 / சங்கீதம் 103"},
            {"day": 10, "book_id": 19, "chapter": 116, "ref": "Psalm 116 / சங்கீதம் 116"},
            {"day": 11, "book_id": 19, "chapter": 121, "ref": "Psalm 121 / சங்கீதம் 121"},
            {"day": 12, "book_id": 19, "chapter": 127, "ref": "Psalm 127 / சங்கீதம் 127"},
            {"day": 13, "book_id": 19, "chapter": 139, "ref": "Psalm 139 / சங்கீதம் 139"},
            {"day": 14, "book_id": 19, "chapter": 145, "ref": "Psalm 145 / சங்கீதம் 145"},
            {"day": 15, "book_id": 19, "chapter": 150, "ref": "Psalm 150 / சங்கீதம் 150"},
        ],
    },
}